### ISSUE TITLE
Ridge detection

### ISSUE THREAD

**Issue by NSQY** [Irrational-Encoding-Wizardry/vsmask#2]
Would something like this be in-scope? I think that, almost always, encoders are looking to mask ridges and not necessarily their boundaries (hence morpho/std.Maximum ...).

https://github.com/WolframRhodium/muvsfunc/wiki/muvs-tutorial#example-ridge-detection
https://dsp.stackexchange.com/a/1735
Some discussion: https://en.wikipedia.org/wiki/Talk:Ridge_detection

**Comment by Ichunjo** [comment]
That's definitely something interesting and would perfectly fit here. I put this in my TODO list while waiting on this issue to be fixed https://github.com/vapoursynth/vapoursynth/issues/847

**Comment by Ichunjo** [comment]
I added the ridge detection to the masks that can support it in the last commits. They're not clamped at all so the results are pretty different between them. A convenience function `get_all_ridge_detect` is also available. My advice is to pass a float clip and then scale it with the `multi` parameter.

Thanks you for your suggestion!
